services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports: ["27017:27017"]
    volumes: ["mongo-data:/data/db"]
  mongo-express:
    image: mongo-express:1
    restart: unless-stopped
    ports: ["8081:8081"]
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
volumes:
  mongo-data:
